source/repos/truYum/truYumC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using truYum.Models;

namespace truYum.Controllers
{
  [AllowAnonymous]
    public class CustomerController : Controller
    {
        truYumContext db = new truYumContext();
        // GET: Customer
        public ActionResult Index()
        {
            var list = db.MenuItems.ToList();
            ViewBag.Clist = db.Categories.ToList();
            return View(list);
        }
        
        public ActionResult Cart(int? id)
        {
            try
            {
                if (id != null)
                {
                    Cart cart = new Cart()
                    {
                        MenuItemId = (int)id
                    };
                    db.Carts.Add(cart);
                    db.SaveChanges();
                    return RedirectToAction("ViewCart");
                }
            }catch(Exception e)
            {
                return View("Error", new HandleErrorInfo(e, "Home", "Error"));
            }
            return View("Cart");

        }
        public class CartList
        {
            public int CartId { get; set; }
            public string Name { get; set; }
            public bool FreeDelivery { get; set; }
            public double Price { get; set; }
        }
        public ActionResult ViewCart() 
        {
            var list = (from cart in db.Carts
                        join menu in db.MenuItems on cart.MenuItemId equals menu.MenuId
                        orderby cart.CartId
                        select new CartList()
                        {
                            CartId=cart.CartId,
                            Name= menu.Name,
                            FreeDelivery=menu.FreeDelivery,
                            Price=menu.Price,
                        }).ToList();
            
            return View(list);
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                Cart Cid = db.Carts.Find(id);
                db.Carts.Remove(Cid);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
            
        }

        }
}

source/repos/truYum/truYumC/Controllers/MenuItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using truYum.Models;

namespace truYum.Controllers
{
    [Authorize]
    public class MenuItemController : Controller
    {
        // GET: MenuItem
        truYumContext db = new truYumContext();
     
        public ActionResult Index()
        {
           
                var list = db.MenuItems.ToList();
                ViewBag.Clist = db.Categories.ToList();
                return View(list);
            
        }

        public ActionResult Create()
        {
            MenuItem menuItem = new MenuItem();

            var list = db.Categories.ToList();
            ViewBag.Catagory = list;

            return View();
        }
        [HttpPost]
        public ActionResult Create(MenuItem menuItem)
        {
            if (ModelState.IsValid)
            {
                db.MenuItems.Add(menuItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                var list = db.Categories.ToList();
                ViewBag.Catagory = list;
                return View();
            }
        }
        public ActionResult Update(int? id)
        {
            MenuItem item = null;
            if (id != null)
            {

                 item = db.MenuItems.Find(id);

               

            }
            var list = db.Categories.ToList();
            ViewBag.Catagory = list;
            return View(item);
        }
        [HttpPost]
        public ActionResult Update(int? id,MenuItem menuItem)
        {
            if (ModelState.IsValid)
            {
                var MenuList = db.MenuItems.Where(x => x.MenuId == id).ToList();
                MenuList.ForEach(x =>
                {
                    x.Name = menuItem.Name;
                    x.FreeDelivery = menuItem.FreeDelivery;
                    x.Price = menuItem.Price;
                    x.Active = menuItem.Active;
                    x.CategoryId = menuItem.CategoryId;
                });
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                var list = db.Categories.ToList();
                ViewBag.Catagory = list;
                return View();
            }
        }
    }
}

source/repos/truYum/truYumC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">




                    @{ if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("MenuItem-Admin", "Index", "MenuItem")</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                            <li>@Html.ActionLink("MenuItem", "Index", "Customer")</li>
                            <li>@Html.ActionLink("Cart", "ViewCart", "Customer")</li>

                        }
                        else
                        {
                            <li>@Html.ActionLink("MenuItem", "Index", "Customer")</li>
                            <li>@Html.ActionLink("Cart", "ViewCart", "Customer")</li>

                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Login", "Login", "Account")</li>
                        }
                    }


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>